### ISSUE TITLE
Discuss what information about the plant should be displayed 

### ISSUE THREAD

**Issue by KaaiiH** [EECE3093C/team-project-weather#12]
The team needs to discuss what information for each plant is going to be displayed on frontend and stored in backend. Team also needs to discuss what specifically should be displayed when a valid location is entered.

- [x] Knowledge of what information for the plant should be displayed
- [x] Knowledge on what parameters will be used to determine if a plant is able to grow or not

**Comment by TheHerbenator** [comment]
The following parameters are available to be used for determining if a plant is able to grow or not:

- Temperature
- Precipitation
- Humidity
- Daily Sunlight
- Pressure
- Wind
- Cloud Coverage

The first 5 of these will likely be used to determine if a plant can grow, whereas the last 2 will not be.

In terms of what other information will be displayed, it was decided that an image of the plant, the name of the plant, the growing season of the plant, and possibly other information such as soil conditions needed, etc. if it is decided that these are necessary in the future.
